import {
  Controller,
  Get,
  Post,
  Delete,
  Body,
  UseGuards,
  Req,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import { ApiTags, ApiOperation, ApiBearerAuth } from '@nestjs/swagger';
import { JwtAuthGuard } from '../../common/guards/jwt-auth.guard';
import { RolesGuard } from '../../common/guards/roles.guard';
import { Roles } from '../../common/decorators/roles.decorator';
import { UserRole } from '@ongc/shared-types';
import { WhatsAppTestService } from './whatsapp-test.service';
import {
  SubmitWhatsAppTestPassDto,
  SendWhatsAppTestMessageDto,
} from './whatsapp-test.dto';

@ApiTags('Admin - WhatsApp Test Lab')
@ApiBearerAuth()
@Controller('admin/employees/whatsapp-test')
@UseGuards(JwtAuthGuard, RolesGuard)
@Roles(UserRole.SUPER_ADMIN)
export class WhatsAppTestController {
  constructor(private readonly testService: WhatsAppTestService) {}

  @Get('config')
  @ApiOperation({
    summary: 'Get WhatsApp Test Lab configuration and provider status',
  })
  async getConfig() {
    return this.testService.getConfig();
  }

  @Post('submit')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary:
      'Submit duplicate test registration and generate isolated test pass with WhatsApp preview',
  })
  async submitTestPass(@Body() dto: SubmitWhatsAppTestPassDto, @Req() req: any) {
    const adminEmail = req?.user?.email || 'SUPER_ADMIN';
    return this.testService.submitTestPass(dto, adminEmail);
  }

  @Post('send')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary:
      'Send WhatsApp test message strictly to configured Super Admin safe test recipient',
  })
  async sendTestMessage(
    @Body() dto: SendWhatsAppTestMessageDto,
    @Req() req: any,
  ) {
    const adminEmail = req?.user?.email || 'SUPER_ADMIN';
    return this.testService.sendTestMessage(dto, adminEmail);
  }

  @Delete('cleanup')
  @ApiOperation({
    summary: 'Clear isolated test data generated by the WhatsApp Test Lab',
  })
  async clearTestData() {
    return this.testService.clearTestData();
  }

  @Post('clear')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Clear isolated test data (POST alias)',
  })
  async clearTestDataPost() {
    return this.testService.clearTestData();
  }
}
